/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/certificates': RouteRecordInfo<
      '/albums/certificates',
      '/albums/certificates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/robocon/': RouteRecordInfo<
      '/albums/robocon/',
      '/albums/robocon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/girls/': RouteRecordInfo<
      '/girls/',
      '/girls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/aupt-package-manager': RouteRecordInfo<
      '/posts/aupt-package-manager',
      '/posts/aupt-package-manager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-valaxy': RouteRecordInfo<
      '/posts/hello-valaxy',
      '/posts/hello-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hexo-blog-guide': RouteRecordInfo<
      '/posts/hexo-blog-guide',
      '/posts/hexo-blog-guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/local-ai-agent-with-ollama': RouteRecordInfo<
      '/posts/local-ai-agent-with-ollama',
      '/posts/local-ai-agent-with-ollama',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/markdown-guide': RouteRecordInfo<
      '/posts/markdown-guide',
      '/posts/markdown-guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/newbowl': RouteRecordInfo<
      '/posts/newbowl',
      '/posts/newbowl',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ubuntu-ros-training': RouteRecordInfo<
      '/posts/ubuntu-ros-training',
      '/posts/ubuntu-ros-training',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/': RouteRecordInfo<
      '/project/',
      '/project',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/2026-h-ti': RouteRecordInfo<
      '/project/2026-h-ti',
      '/project/2026-h-ti',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/aepd': RouteRecordInfo<
      '/project/aepd',
      '/project/aepd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/agent-robot-framework': RouteRecordInfo<
      '/project/agent-robot-framework',
      '/project/agent-robot-framework',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/agentos': RouteRecordInfo<
      '/project/agentos',
      '/project/agentos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/aupt': RouteRecordInfo<
      '/project/aupt',
      '/project/aupt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/examguard': RouteRecordInfo<
      '/project/examguard',
      '/project/examguard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/kali-tools-reference': RouteRecordInfo<
      '/project/kali-tools-reference',
      '/project/kali-tools-reference',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/ollama-ai': RouteRecordInfo<
      '/project/ollama-ai',
      '/project/ollama-ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/openclaw': RouteRecordInfo<
      '/project/openclaw',
      '/project/openclaw',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/rc-legged-training-simulation': RouteRecordInfo<
      '/project/rc-legged-training-simulation',
      '/project/rc-legged-training-simulation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/robocon': RouteRecordInfo<
      '/project/robocon',
      '/project/robocon',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/robot_viewer': RouteRecordInfo<
      '/project/robot_viewer',
      '/project/robot_viewer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/robot-hermes-skill': RouteRecordInfo<
      '/project/robot-hermes-skill',
      '/project/robot-hermes-skill',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/software-cup-fire-detection': RouteRecordInfo<
      '/project/software-cup-fire-detection',
      '/project/software-cup-fire-detection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/software-cup-object-detection': RouteRecordInfo<
      '/project/software-cup-object-detection',
      '/project/software-cup-object-detection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/solidworks-design-collection': RouteRecordInfo<
      '/project/solidworks-design-collection',
      '/project/solidworks-design-collection',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/project/wheelleg-fullstack-challenge': RouteRecordInfo<
      '/project/wheelleg-fullstack-challenge',
      '/project/wheelleg-fullstack-challenge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.27.0_@babel+parser@7.29.0_@nuxt+kit@3.21.1_@types+markdown-it@14.1.2_@types+node@25._m6vdmsdbslbvqtzibdkj34xau4/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/albums/index.md': {
      routes:
        | '/albums/'
      views:
        | never
    }
    'pages/albums/certificates.md': {
      routes:
        | '/albums/certificates'
      views:
        | never
    }
    'pages/albums/robocon/index.md': {
      routes:
        | '/albums/robocon/'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/girls/index.md': {
      routes:
        | '/girls/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.27.0_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/aupt-package-manager.md': {
      routes:
        | '/posts/aupt-package-manager'
      views:
        | never
    }
    'pages/posts/hello-valaxy.md': {
      routes:
        | '/posts/hello-valaxy'
      views:
        | never
    }
    'pages/posts/hexo-blog-guide.md': {
      routes:
        | '/posts/hexo-blog-guide'
      views:
        | never
    }
    'pages/posts/local-ai-agent-with-ollama.md': {
      routes:
        | '/posts/local-ai-agent-with-ollama'
      views:
        | never
    }
    'pages/posts/markdown-guide.md': {
      routes:
        | '/posts/markdown-guide'
      views:
        | never
    }
    'pages/posts/newbowl.md': {
      routes:
        | '/posts/newbowl'
      views:
        | never
    }
    'pages/posts/ubuntu-ros-training.md': {
      routes:
        | '/posts/ubuntu-ros-training'
      views:
        | never
    }
    'pages/project/index.md': {
      routes:
        | '/project/'
      views:
        | never
    }
    'pages/project/2026-h-ti.md': {
      routes:
        | '/project/2026-h-ti'
      views:
        | never
    }
    'pages/project/aepd.md': {
      routes:
        | '/project/aepd'
      views:
        | never
    }
    'pages/project/agent-robot-framework.md': {
      routes:
        | '/project/agent-robot-framework'
      views:
        | never
    }
    'pages/project/agentos.md': {
      routes:
        | '/project/agentos'
      views:
        | never
    }
    'pages/project/aupt.md': {
      routes:
        | '/project/aupt'
      views:
        | never
    }
    'pages/project/examguard.md': {
      routes:
        | '/project/examguard'
      views:
        | never
    }
    'pages/project/kali-tools-reference.md': {
      routes:
        | '/project/kali-tools-reference'
      views:
        | never
    }
    'pages/project/ollama-ai.md': {
      routes:
        | '/project/ollama-ai'
      views:
        | never
    }
    'pages/project/openclaw.md': {
      routes:
        | '/project/openclaw'
      views:
        | never
    }
    'pages/project/rc-legged-training-simulation.md': {
      routes:
        | '/project/rc-legged-training-simulation'
      views:
        | never
    }
    'pages/project/robocon.md': {
      routes:
        | '/project/robocon'
      views:
        | never
    }
    'pages/project/robot_viewer.md': {
      routes:
        | '/project/robot_viewer'
      views:
        | never
    }
    'pages/project/robot-hermes-skill.md': {
      routes:
        | '/project/robot-hermes-skill'
      views:
        | never
    }
    'pages/project/software-cup-fire-detection.md': {
      routes:
        | '/project/software-cup-fire-detection'
      views:
        | never
    }
    'pages/project/software-cup-object-detection.md': {
      routes:
        | '/project/software-cup-object-detection'
      views:
        | never
    }
    'pages/project/solidworks-design-collection.md': {
      routes:
        | '/project/solidworks-design-collection'
      views:
        | never
    }
    'pages/project/wheelleg-fullstack-challenge.md': {
      routes:
        | '/project/wheelleg-fullstack-challenge'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
